version: '3.8'

services:
  nordvpn:
    image: bubuntux/nordvpn
    container_name: nordvpn
    environment:
      - USERNAME=michaelrennie999@gmail.com  # Replace with your NordVPN username
      - PASSWORD=Butterfly135!#%  # Replace with your NordVPN password
      - COUNTRY=Japan           # Replace with your desired country
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      - vpn-network
    restart: unless-stopped
  node-app:
    image: your-dockerhub-username/your-node-app:latest
    build: .
    depends_on:
      - nordvpn
    environment:
      - NODE_ENV=production
    networks:
      - vpn-network
    restart: unless-stopped
    logging:
      driver: gcplogs
      options:
        gcp-project: wellwash-411511

  # Portainer service for container management
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"  # Portainer web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Access Docker daemon
      - portainer_data:/data  # Persistent storage for Portainer

# Volumes for persistent data
volumes:
  portainer_data:
networks:
  vpn-network:
    driver: bridge